pksunkara/octonode

README.md
lib/octonode/org.js
src/octonode/org.coffee

This adds support for the "check public membership" API exposed to organizations, which I'm now using in an app.
Documented here: https://developer.github.com/v3/orgs/members/#check-public-membership

Adding the API to check an org member's public membership choice.

---

README.md
lib/octonode/issue.js
lib/octonode/me.js
lib/octonode/org.js
lib/octonode/team.js
src/octonode/issue.coffee
src/octonode/me.coffee
src/octonode/org.coffee
src/octonode/team.coffee

Hi,
This PR contains a number of additional GitHub V3 API calls that I implemented back in February and March. Given the units of work are independent and represent different API calls, I have no squashed many commits together. Happy to change that if you prefer.
APIs implemented include:
- Issue APIs:     
- Creating a comment
- Updating a comment
- Deleting a comment
- "Me" API:
- Listing the authenticated user's team memberships
- Organization APIs:
- Publicizing a user's org membership   
- Concealing a user's org membership
- Removing a member from an organization
- Team APIs:
- Updating a team 
- Checking for the membership of a user in a team
- Adding team membership           
- Removing team membership
Thanks,
Jeff

Implementing additional GitHub APIs

---

lib/octonode/auth.js
lib/octonode/gist.js
src/octonode/auth.coffee

That's my first coffeescript coding... Don't know how to compile that though.

Check err before reading res. Fixes #186.

---

README.md
lib/octonode/repo.js
src/octonode/repo.coffee

This change uses PATCH to edit a repo. This can be used to change the description of a repo, change it from private to public, etc.

Adding `repo.update` functionality

---

src/octonode/org.coffee

https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership

add api to create membership in org

---

lib/octonode/org.js
src/octonode/org.coffee

This fixes the response code per the GitHub API documentation and test use for the `ghorg.addTeamRepo` function.
Also improves the comment to better describe as GitHub does what the function call does.
Note, `cake lib` was generating a function from a previous commit of another use for a function `addMember`, so I have included this here for now. LMK if I should not include the generated bit.

Fixing the expected response code from ghorg.addTeamRepo

---

lib/octonode/team.js
src/octonode/team.coffee

Hi,
This is an initial PR but likely we will want to iterate. I wanted to get your initial feedback related to the new GitHub organization management system that began broadly rolling out yesterday - [details here](https://github.com/blog/2064-new-organization-permissions-now-available).
A few things:
- The status code returned by the API for the membership check is different for the new system and old... for in the interim I've considered accepting HTTP 200 _and_ 204. (200 new, 204 old)
- There is now a `state` property and object associated with a membership check. As a result, instead of breaking the old experience (a true/false return value), I've added yet another method to return that. Not sure what your thoughts are on that.
Will also comment inline...
Thanks for your thoughts, …

Updating APIs for the newer GitHub organization management system

---

lib/octonode/team.js
src/octonode/team.coffee

Team Get Members API: supporting the new organization system by providing a custom Accept header allowing the 'role' parameter to be passed in for filtering the team members.
The body of the response is identical, however supplying `role` as a filtering parameter for the method only actually filters when sending the preview API Accept header. In time this will not be required.
API documentation: https://developer.github.com/v3/orgs/teams/#list-team-members

Team Get Members API: supporting the new organization system

---

lib/octonode/repo.js
src/octonode/repo.coffee

Hi,
This updates the repo `collaborators` method. Right now, the method is unable to accept paging parameters (per_page or page), so it only returns the first 100 collaborators.
Since the method has a switch experience for a provided username, passing the object with the filter parameters does not work.
This proposes a way to work around that: if the callback/user value is an object, then it is sent as the param to the get request.
This also updates the API to use the new GitHub organization API system; at this time, it just sends back an additional permission value for each user, whether they have admin/pull/push rights, but no other changes. Documented here: https://developer.github.com/v3/repos/collaborators/#list
Thoughts?
Thanks,
Jeff

Updating repo collaborators to support paging objects.

---

lib/octonode/client.js
lib/octonode/org.js
src/octonode/client.coffee
src/octonode/org.coffee

Hi,
With the new GItHub org management system, all teams now have per-repo granularity of permission - admin, pull, push; previously, the entire team had a specific level of permission.
This change is:
- Extending the standard `put` client code path to support an options parameter. This felt cleaner than duplicating the entire `put` method to then have a `putOptions` method, but this does mean it is not exactly the same as the get/getOptions split in the client.coffee file.
- Updates the org `addTeamRepo` method to take an optional parameter piece, where you could specify the permission per the API at https://developer.github.com/v3/orgs/teams/#add-team-repo
I've spoken with GitHub, and although everyone has been moved to the new GitHub org management system, their API system still …

Add team repo support for the new granularity of GitHub org mgmt

---

lib/octonode/me.js
src/octonode/me.coffee

Hi,
Looking for feedback on the method name here. It's odd because the API feels generic, but has a very restrictive use, sending a single state parameter.
The API is: https://developer.github.com/v3/orgs/members/#edit-your-organization-membership

Allowing the user to patch their org membership.

---

README.md

I thought it might be useful to add an example on how to build a client from a different host. For example to connect to a GitHub Enterprise instance. Currently this feature is kind of hidden although it was mentioned in some issues. I also fixed a typo.

Added usage to build client from different host

---

README.md

Just a small typo fix. Took a while trying to debug what was wrong with my code and realized there was a typo in the documentation.

Fix typo in README.md for org membership

---

lib/octonode/auth.js
src/octonode/auth.coffee

While working with this API I received a callback with neither a token nor an error -- stepping through `login()` this was caused by a non-401 error (specifically a 403 with this body: `"{"message":"This API can only be accessed with username and password Basic Auth","documentation_url":"https://developer.github.com/v3/oauth_authorizations/#oauth-authorizations-api"}"`)

Treat any status other than 201 as error

---

package.json

request had a bad dependency on hawk 
```
"vulnerabilities": [
{
"name": "hawk",
"version": "1.1.1",
"path": "octonode@0.7.5 => request@2.51.0 => hawk@1.1.1",
"patchTo": ">=3.1.3 < 4.0.0 || >=4.1.1",
"problem": "Regular Expression Denial of Service"
}
]
```
Other modules were bumped for convenience

updates depends based on  node security advisory report

---

package.json

> to allow news dependencies to take effect
0.7.5 should be deprecated because it requires a package with a vulnerability.

bumps version

---

README.md

Adds documentation to the README outlining how to use two-factor authentication whilst performing auth via the CLI mode.
This is in relation to me trying to figure out how this worked earlier with issue #250. Thanks @pksunkara for pointing me in the right direction.

Add two-factor auth cli documentation

---

README.md
src/octonode/repo.coffee

Added support for getting the combined status for a specific ref (https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref).
@pksunkara

Add support for getting combined status for a ref

---

package.json
src/octonode/client.coffee

All promise based methods have "Async" suffix. For example: 
`client.user(username).followers(callback)` 
becomes 
`client.user(username).followersAsync().then().catch()`
This change takes advantage of[ Bluebird's Promise.promisifyAll() method.](http://bluebirdjs.com/docs/api/promise.promisifyall.html) 
These changes are non-breaking for existing users of Octonode, but will allow new projects to take advantage of promise chaining. If this PR looks good, I'd be happy to update the readme.
Resolves #139

Add promise based methods to client class and subclasses

---

lib/octonode/repo.js
src/octonode/repo.coffee

Allow the ability to pass optional parameters such as commiter and author to updateContents

Allow parameters in repo.updateContents

---

README.md

`add_scopes` doesn't work. changing the readme to reflect the working attribute `scopes`

fix add_scopes to scopes

---

lib/octonode/repo.js
src/octonode/repo.coffee

This adds support for [this endpoint](https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name)

Support looking up a release by tag name
