- lib/octonode/team.js
- src/octonode/team.coffee
Hey Pavan,
I'd like to add params support to the team repo wrapper. Our teams have > 30 repos and would like to have this available in octonode.
Thanks!
>  add params support to team repos function

- src/octonode/team.coffee
Team members endpoint can optionally be paginated :page_with_curl:
> Added pagination for team members endpoint

- lib/octonode/repo.js
- src/octonode/repo.coffee
https://developer.github.com/v3/repos/statistics/#contributors
> Added repo.contributorsStats() method

- lib/octonode/auth.js
- src/octonode/auth.coffee
github oauth supports different sub paths of the official callback: https://developer.github.com/v3/oauth/
> added redirect_uri parameter to authentication call (including lib folder)

- lib/octonode/gist.js
- lib/octonode/me.js
- lib/octonode/repo.js
- src/octonode/gist.coffee
- src/octonode/me.coffee
- src/octonode/repo.coffee
> Fix Gist::delete

- lib/octonode/repo.js
- src/octonode/repo.coffee
This was breaking my app when trying to delete a hook. tiny error. But an annoying and breaking one.
> added empty content object to deleteHook call

- README.md
- src/octonode/team.coffee
As documented at https://developer.github.com/v3/orgs/teams/#remove-team-member
Note that "user" can be both a standard user or an org.
> Added teams/removeRepo function

- README.md
- lib/octonode/repo.js
- src/octonode/repo.coffee
I have written the javascript implementation of create reference and updated the readme. My coffeescript is rusty so I have skipped that part. Would like to know your views before I contribute more.
> written function to create reference

- lib/octonode/repo.js
- src/octonode/repo.coffee
This adds 2 collaborator APIs for repos, including updates for the new organization system.
Add: takes an optional parameter/options object, enables setting a `permission` field, for example.
Delete: pretty straightforward
Thanks,
Jeff
> Add collaborator. Delete collaborator.

- .gitignore
- README.md
- lib/octonode/repo.js
- src/octonode/repo.coffee
This addresses #220.
Decided to take a stab at my own suggestion, I looked at the unit tests, but don't have time right now to shore that up. I can also squash this if you'd like.
> Adds Repo.compare()

- README.md
- lib/octonode/auth.js
- src/octonode/auth.coffee
Made hard-coded github.com urls options that can be overwritten. 
Unsure if underscores or camelCase was better for option names, please change to fit style. Thanks
> Support Github enterprise for authentication

- README.md
- lib/octonode/org.js
- lib/octonode/repo.js
- src/octonode/org.coffee
- src/octonode/repo.coffee
@pksunkara I have added the API calls for organizations in coffee script for your review.
Please let me know what you think.  Thanks!
> Hook functionality for Organizations

- README.md
Added ghuser.repos docs to readme as the it was already implemented, but not added to readme.
> Updated README: ghuser.repos

- README.md
- lib/octonode/client.js
- src/octonode/client.coffee
How to use
```js
var organisations = client.get('/organizations', 2000, 100, true);
var organisations = client.get('/users', 2000, 100, true);
```
In reference to https://github.com/pksunkara/octonode/issues/241
> Added support for since based pagination

- lib/octonode/issue.js
- lib/octonode/label.js
- src/octonode/issue.coffee
- src/octonode/label.coffee
> Adds Unicode support for labels

- lib/octonode/repo.js
- src/octonode/repo.coffee
IMHO it is not yet possible to delete a reference or especially a branch.
See the github documentation:
https://developer.github.com/v3/git/refs/#delete-a-reference
> Add possibility to delete refs

- README.md
- lib/octonode/auth.js
- src/octonode/auth.coffee
resolves #297
Let me know if you want me to do something similar in the `web` login flow
basically, changed the login function to this:
```js
var scopes = {
'add_scopes': ['user', 'repo', 'gist'],
'note': 'admin script'
};
github.auth.config({
username: 'pksunkara',
password: 'password'
}).login(scopes, function (err, id, token, headers) {
console.log(id, token);
});
```
> [ISSUE #297] return headers in login callback for authentication

- README.md
- lib/octonode/repo.js
- src/octonode/repo.coffee
Hi,
I'm using this package for internal tool and needed an ability to create a merge, so I've added it quickly based on [this api doc](https://developer.github.com/v3/repos/merging/#perform-a-merge).
Maybe it can be useful to anyone else.
Cheers!
> Github Merge API - Merge branch

- lib/octonode/team.js
- src/octonode/team.coffee
Added support for https://developer.github.com/v3/orgs/teams/#add-or-update-team-repository
> Add support for adding teams to repos

- lib/octonode/repo.js
- src/octonode/repo.coffee
Used the wrong param for the path, should be `repo` and not `name`
> Fixed merges API path

- lib/octonode/issue.js
- lib/octonode/pr.js
- src/octonode/issue.coffee
- src/octonode/pr.coffee
Hi @pksunkara, thank you for this project.
Hopefully I have understood correctly, but I noticed that `ghpr.comments` did not behave the same as `ghissue.comments` so I have made `ghpr.comments` paginated in the same way. 
I have also added a paginated `ghpr.events` which fetches data from `https://api.github.com/repos/{repo}/issues/{number}/events`.
Hope this helps, thanks,
Jamie
> Paginated PR Comments and Issue Events

- package.json
See https://snyk.io/vuln/npm:deep-extend:20180409
> Update deep-extend to fix vulnerability

- README.md
https://github.com/pksunkara/octonode/issues/314
> Updated Readme to include Async functions

- README.md
> Correct typo in readme: uploadAssets

- README.md
1. edit linnk to more kind and detail link
2. add descriptions 'maximum is 100' 
first thank you for your work!!
i used this for my projects 
when i used this i missed description about pagination
so how about add more description and edit more latest link for another users
if this accepted i will check more part of this library 
thank you for your work!!! 😃
> edit link and add more description
